#mkpasswd -m sha-512
#apt-get install  cloud-image-utils
#cloud-localds seed-init.iso user-data

#cloud-config
system_info:
  default_user:
    name: kuser
    sudo: ALL=(ALL) NOPASSWD:ALL
password: Kdemo@1
chpasswd: { expire: False }
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUwngQBA69ltXWTyFV1Z5/YmuQJR+DMQEuZWYVgXtAzCNFlGnisFzSjGlF27qPrNDgAKzMjtw6XPH9Q4o0aqvqE4k9gtSEk1AYsFuoIHq5xonxHoyjgv+6rSQB3J+mXNIIaR8WIg1yQLOvUSnGsTpLlDHxQbRMr2vNoja2BlDkR4PqlPTlFaGLlk2OyKBDY6xH9ikH+V3y+mTJSa+pzXSpNpMWm0wO4mZChAoZmrcco+CJWe8kI3JS+0uOvqX3d73tuAMrdE4lvU1av6QiLSsHA/NearA8aU+oOHlsUdv/wQCU+TEfXF0SWD4KQZN8brVvNx4t/or849vxvV2ycpxP monzu@dust

ssh_pwauth: True

packages:
  - openssh-server
  - socat
  - net-tools
  - iproute2
  - unzip

runcmd:
  - systemctl enable ssh
  - systemctl start ssh
